# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('pick_lat', models.FloatField(max_length=100)),
                ('pick_lon', models.FloatField(max_length=100)),
                ('drop_lat', models.FloatField(max_length=100)),
                ('drop_lon', models.FloatField(max_length=100)),
                ('passenger', models.IntegerField()),
                ('start_time', models.DateTimeField(default=True)),
                ('end_time', models.DateTimeField(default=True)),
                ('trip_dist', models.FloatField(default=True, max_length=10)),
            ],
        ),
    ]
